--DROP DATABASE IF EXISTS HelpDesk-- ELIMINAR DB ANTES
CREATE DATABASE HelpDesk
USE HelpDesk

CREATE TABLE T_EMPRESA(
ID_EMPRESA numeric(10) identity (1,1),
NOMBRE_COMERCIAL nvarchar(150),
NIT nvarchar(20),
DIRECCION nvarchar(150),
TELEFONO nvarchar(12),
CORREO nvarchar(60),
CONSTRAINT PK_ID_EMPRESA PRIMARY KEY (ID_EMPRESA)
);

CREATE TABLE T_USUARIO(
ID_USUARIO numeric (10) identity (1,1),
USUARIO nvarchar (20),
CONTRASEÑA nvarchar (30),
CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE T_EMPLEADO(
ID_EMPLEADO numeric (10) identity (1,1),
ID_USUARIO numeric(10),
NOMBRES nvarchar(60),
IDENTIFICACION nvarchar(20),
CORREO nvarchar(60),
PUESTO nvarchar(30),
CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
CONSTRAINT FK_ID_EMPLEADO_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO (ID_USUARIO),
);

CREATE TABLE T_SOLICITANTE(
ID_SOLICITANTE numeric(10) identity (1,1),
ID_USUARIO numeric(10),
ID_EMPRESA numeric (10),
NOMBRES nvarchar(60),
IDENTIFICACION nvarchar(20),
CORREO nvarchar(60),
CONSTRAINT PK_ID_SOLICITANTE PRIMARY KEY (ID_SOLICITANTE),
CONSTRAINT FK_ID_SOLICITANTE_ID_EMPRESA FOREIGN KEY (ID_EMPRESA)  REFERENCES T_EMPRESA (ID_EMPRESA),
CONSTRAINT FK_ID_SOLICITANTE_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIO (ID_USUARIO),
);


CREATE TABLE T_HARDWARE(
ID_HARDWARE numeric (10) identity (1,1),
TIPO_HARDWARE nvarchar (150),
CONSTRAINT PK_ID_HARDWARE PRIMARY KEY (ID_HARDWARE),
);

CREATE TABLE T_SOFTWARE(
ID_SOFTWARE numeric (10) identity (1,1),
TIPO_SOFTWARE nvarchar (150),
CONSTRAINT PK_ID_SOFTWARE PRIMARY KEY (ID_SOFTWARE),
);

/*FECHA_INCIDENCIA WAS CHANGED TO VARCHAR*/
CREATE TABLE T_INCIDENCIA(
ID_INCIDENCIA numeric (10) identity (100,1),
ID_HARDWARE numeric (10),
ID_SOFTWARE numeric (10),
FECHA_INCIDENCIA nvarchar (20), 
ESTADO nvarchar(20),
CONSTRAINT PK_ID_INCIDENCIA PRIMARY KEY (ID_INCIDENCIA),
CONSTRAINT FK_ID_INC_ID_HARDWARE FOREIGN KEY (ID_HARDWARE) REFERENCES T_HARDWARE (ID_HARDWARE),
CONSTRAINT FK_ID_INC_ID_SOFTWARE FOREIGN KEY (ID_SOFTWARE) REFERENCES T_SOFTWARE (ID_SOFTWARE)
);

/*FECHA_ATENCION_IN  WAS CHANGED TO VARCHAR*/
CREATE TABLE T_ATENCION_INCIDENCIA(
ID_ATENCION_IN numeric (10) identity (1,1),
ID_INCIDENCIA numeric(10),
ID_SOLICITANTE numeric (10),
ID_EMPLEADO numeric(10),
FECHA_ATENCION_IN nvarchar (20),
OBSERVACIONES nvarchar (200),
ESTADO nvarchar (20),
CONSTRAINT PK_ID_ATENCION_IN PRIMARY KEY (ID_ATENCION_IN),
CONSTRAINT FK_ID_INCIDENCIA FOREIGN KEY (ID_INCIDENCIA) REFERENCES T_INCIDENCIA (ID_INCIDENCIA),
CONSTRAINT FK_ID_ATENCION_ID_SOLICITANTE FOREIGN KEY (ID_SOLICITANTE) REFERENCES T_SOLICITANTE (ID_SOLICITANTE),
CONSTRAINT FK_ID_ATENCION_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES T_EMPLEADO (ID_EMPLEADO)
);